services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\ArticleFeed\LuigisBoxBundle\:
        resource: '../../*'

    Shopsys\ArticleFeed\LuigisBoxBundle\LuigisBoxArticleFeed:
        tags:
            - { name: shopsys.feed, hours: '*', minutes: '30' }
